version: '3.1'

services:
  web:
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./config/odoo.prod.conf:/etc/odoo/odoo.conf
      - odoo_web_data:/var/lib/odoo
    restart: always

  db:
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo_web_data:
  odoo_db_data:
