[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$xBgDAOBcK.Uco3SOcQ6BMA$ayVXdUjQUBT.29du9jKlPqBr1PLUYbGH/Utm5G.1wfsmOak4lcjJ4BAtU9r1sSziXL/aSvSm4E11RhCJbW0v4w
db_host = db
db_user = odoo
db_password = odoo
limit_memory_hard = 0
limit_memory_soft = 0
limit_request = 0
limit_time_cpu = 0
limit_time_real = 0
max_cron_threads = 1
workers = 0

